# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=140)),
                ('photo_link', models.URLField(blank=True)),
                ('photo', models.ImageField(max_length=45, upload_to='uploads/featured/')),
            ],
            options={
                'verbose_name': 'Featured Header',
                'verbose_name_plural': 'Featured Headers',
            },
        ),
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name_plural': 'Blog and Docs'},
        ),
        migrations.AlterField(
            model_name='doc',
            name='publishedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=45, upload_to='uploads/projects/'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='publishedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
