# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0002_auto_20170830_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredheader',
            name='photo',
            field=models.ImageField(blank=True, max_length=45, upload_to='uploads/featured/'),
        ),
        migrations.AlterField(
            model_name='featuredheader',
            name='photo_link',
            field=models.URLField(),
        ),
    ]
