# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0005_doc_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doc',
            old_name='programmingLanguages',
            new_name='programmingLanguage',
        ),
        migrations.AlterField(
            model_name='doc',
            name='publishedDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
