# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0009_person_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='board_member',
            field=models.BooleanField(default=False),
        ),
    ]
