# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0011_auto_20170908_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='author_bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='doc',
            name='programmingLanguage',
            field=models.CharField(choices=[('rb', 'Ruby'), ('py', 'Python'), ('sh', 'ShellScript'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('ru', 'Rust'), ('swift', 'Swift'), ('m', 'Objective-C'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('web', 'HTML, CSS, JavaScript'), ('as', 'Apple Script'), ('r', 'R')], default='py', max_length=5),
        ),
    ]
