# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0012_auto_20170908_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='author_bio',
            field=models.TextField(blank=True, max_length=550),
        ),
    ]
