# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0015_auto_20171013_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
