# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0018_remove_audio_publisheddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(max_length=45, upload_to='uploads/profiles/'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='artwork',
            field=models.ImageField(max_length=45, upload_to='uploads/projects/'),
        ),
    ]
