# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0019_auto_20171025_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
