# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0020_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='slug',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='doc',
            name='programmingLanguage',
            field=models.CharField(choices=[('code', 'Coding'), ('NewsViewController', 'Notícias'), ('exp', 'Experimentos'), ('aulas', 'Aulas'), ('rb', 'Ruby'), ('py', 'Python'), ('sh', 'ShellScript'), ('md', 'Markdown'), ('c', 'C'), ('cpp', 'C++'), ('csp', 'C#'), ('java', 'Java'), ('ru', 'Rust'), ('swift', 'Swift'), ('m', 'Objective-C'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('web', 'HTML, CSS, JavaScript'), ('node', 'NodeJS'), ('dj', 'Django'), ('rails', 'Ruby on Rails'), ('as', 'Apple Script'), ('r', 'R')], default='py', max_length=5),
        ),
    ]
