# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-06 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EKSite', '0023_auto_20180106_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='projectName',
            new_name='related_project',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='projectName',
            new_name='related_project',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='projectName',
            new_name='related_project',
        ),
    ]
